# action.yaml
name: "Guacamole GitHub Action"
author: "Benjamin Sanvoisin"
description: "A github action to check your terraform code with guacamole"
inputs:
  check_type:
    default: "static"
    description: "Type of check to perform"
    required: false
  path:
    default: "."
    description: "Path with infrastructure code and/or package manager files to scan"
    required: false
  verbose:
    default: "false"
    description: "Verbose mode"
    required: false

runs:
  using: docker
  image: docker://ghcr.io/padok-team/guacamole:v0.2.0
  args:
    - "${{ inputs.check_type }}"
    - "-p=${{ inputs.path }}"
    - "-v=${{ inputs.verbose }}"
